apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: project-b
  labels:
    app: webapp
    environment: dev
spec:
  type: LoadBalancer
  ports:
    - name: webport
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: samplewebapp
    environment: dev