apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  namespace: project-b
  labels:
    app: sampleapp
    environment: dev
spec:
  containers:
    - name: testcon
      image: 088310115913.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          protocol: TCP
          name: webport
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"




